### ISSUE TITLE
current master does not compile on kernel 4.4.0

### ISSUE THREAD

**Issue by mischief** [OpenAoE/aoe#6]
the major issue seems to be that `BIO_UPTODATE` is gone in recent kernels.

```
/home/mischief/src/aoe/linux/drivers/block/aoe/aoecmd.c: In function ?aoe_failbuf?:
/home/mischief/src/aoe/linux/drivers/block/aoe/aoecmd.c:1723:12: error: ?BIO_UPTODATE? undeclared (first use in this function)
  clear_bit(BIO_UPTODATE, &buf->bio->bi_flags);
            ^
```

attached is a report zip.

if other info is required, let me know.

[aoe6-87pre2-report.zip](https://github.com/OpenAoE/aoe/files/171204/aoe6-87pre2-report.zip)

**Comment by mischief** [comment]
i think this can be fixed by upstream commit torvalds/linux@4246a0b63bd8f56a1469b12eafeb875b1041a451

**Comment by ecashin** [comment]
I've started a v87pre3-bi_error branch for this work.  The only tricky part so far is an interaction between the changes addressed in conf/41 and these new changes, but that is fairly routine stuff.

**Comment by ecashin** [comment]
Hi.  I have gotten no feedback on this work yet.

Anyone interested in this new support, please report on the branch I created, v87pre3-bi_error.  If you want help trying the branch, please let me know.

**Comment by kalleyne** [comment]
Hello.
I downloaded aoe-87pre3-bi_error.zip. This compiles fine on kernel 4.4.0-62-generic. It taints the kernel but otherwise allows connectivity to vblade.

**Comment by ecashin** [comment]
That's great news, thanks.  Is the taint because it's not signed, or is there some other reason listed?  I don't remember seeing taint before.

**Comment by kalleyne** [comment]
Tried compilation again but this time with 4.4.0-63-generic. Seems to be ok. dmesg show this:

[ 3505.991811] aoe: module verification failed: signature and/or required key missing - tainting kernel
[ 3505.993377] aoe: AoE v87pre3 initialised.

**Comment by kalleyne** [comment]
Tried using make on aoe-87pre3-bi_error with 4.8.0-36-generic. Some new errors:

make
cd aoetools-36 && make 
make[1]: Entering directory '/home/user1/IMG/Coraid/aoe/aoe-87pre3-bi_error/aoetools-36'
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-discover.in
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-interfaces.in
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-mkshelf.in
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-revalidate.in
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-flush.in
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-stat.in
cc -Wall -O -g -o aoeping.o -c aoeping.c
aoeping.c: In function ‘smart’:
aoeping.c:331:6: warning: variable ‘n’ set but not used [-Wunused-but-set-variable]
  int n;
      ^
cc -Wall -O -g -o linux.o -c linux.c
cc -Wall -O -g -o aoeping aoeping.o linux.o
cc -Wall -O -g -o aoecfg.o -c aoecfg.c
cc -Wall -O -g -o aoecfg aoecfg.o linux.o
cc -Wall -O -g -o aoe-sancheck.o -c aoe-sancheck.c
aoe-sancheck.c: In function ‘jinput’:
aoe-sancheck.c:277:7: warning: variable ‘aa’ set but not used [-Wunused-but-set-variable]
  Ata *aa;
       ^
aoe-sancheck.c: In function ‘sancheck’:
aoe-sancheck.c:614:11: warning: variable ‘mtuflag’ set but not used [-Wunused-but-set-variable]
  int mtu, mtuflag;
           ^
cc -Wall -O -g -o aoe-sancheck aoe-sancheck.o -lpthread
make[1]: Leaving directory '/home/user1/IMG/Coraid/aoe/aoe-87pre3-bi_error/aoetools-36'
sh -c "cd linux/drivers/block/aoe && rm -f *.o *.ko core"
ensuring compatibility ... 1 
patching file linux/drivers/block/aoe/disk_attr.h
2 3 4 5 6 
patching file linux/drivers/block/aoe/aoecmd.c
Hunk #1 succeeded at 978 with fuzz 1 (offset 222 lines).
7 8 9 
patching file linux/drivers/block/aoe/aoeblk.c
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- saving rejects to file linux/drivers/block/aoe/aoeblk.c.rej
patching file linux/drivers/block/aoe/aoecmd.c
Hunk #1 FAILED at 672.
1 out of 1 hunk FAILED -- saving rejects to file linux/drivers/block/aoe/aoecmd.c.rej
Makefile:74: recipe for target 'conf/done' failed
make: *** [conf/done] Error 1

**Comment by kalleyne** [comment]
Now trying Ubuntu 16.04.2 LTS Desktop AMD64. uname -a shows "4.4.0-64-generic". This is a fresh install, patches applied. Both make and make install inside of aoe-87pre3-bi_error directory appears to complete error free. However, modprobe fails: "modprobe: ERROR: could not insert 'aoe': Required key not available".

Thanks.

**Comment by ecashin** [comment]
Can you please create a new issue for the  4.8.0-36-generic support?  It is different from the support for the 4.4.0 kernel this issue covers.

Also, the key requirement is a new, unrelated issue.  If you create an issue for that one, please include the final lines of the dmesg output along with your report.

**Comment by kalleyne** [comment]
I re-tested 4.4.0-64-generic and aoe-87pre3-bi_error but this time on Ubuntu 16.04.2 Server LTS - No HWE.  Can't seem to reproduce the key requirement - unrelated issue anyway as you suggested...so I'll create a new issue if it happens again. But the dmesg shows this:

[   38.378902] aoe: module verification failed: signature and/or required key missing - tainting kernel
[   38.379768] aoe: AoE v87pre3 initialised.
[   38.380063] aoe: e0.0: setting 1024 byte data frames

**Comment by ecashin** [comment]
Searching for the required key error yields threads about UEFI secure boot like the one at the URL below.

http://askubuntu.com/questions/762254/why-do-i-get-required-key-not-available-when-install-3rd-party-kernel-modules

I haven't looked into signing the aoe driver.  It's a good idea, even though the driver has never been signed, so this is a new warning about an old problem.  If it is important to you, please make an issue for driver signatures, and I'll look into it, but I am not sure how it could work with aoe's approach.  We have always dynamically patched the source for whatever target kernel is being used.  We don't currently distribute binaries at this time.

**Comment by ecashin** [comment]
I've merged this branch now and am closing the issue.
